SRC_URI:append = " \
	file://0000-compulab-em9190-Add-modem-driver.patch \
	file://0001-compulab-ili9881c-Add-panel-driver.patch \
	file://0002-compulab-winbond-Add-w25q128dw-support.patch \
	file://0003-compulab-dts-Add-device-trees.patch \
	file://0004-compulab-configs-Add-compulab-soms-configs.patch \
	file://0005-compulab-imx8mp-dts-Update-device-tree-files.patch \
	file://0006-compulab-Add-econ-cameras-support.patch \
	file://0007-ucm-imx8m-plus-defconfig-Disable-CONFIG_FW_LOADER_US.patch \
	file://defconfig \
"
