require ucm-imx8m-plus.conf
require include/device-tree/iotdin-imx8p.inc
require include/device-tree/iot-gate-imx8plus.inc
require include/device-tree/mcm-imx8m-plus.inc
require include/device-tree/som-imx8m-plus.inc
require include/device-tree/ucm-imx8m-plus.inc
require include/device-tree/ucm-imx8m-plus-sbev.inc

WKS_BOOT_SIZE = "256M"

CORE_IMAGE_EXTRA_INSTALL += " compulab-bootloader cl-firmware "
RM_WORK_EXCLUDE += "compulab-bootloader"
