#@TYPE: Machine
#@NAME: CompuLab IOTDIN-IMX8PLUS - Industrial IoT Gateway
#@SOC: i.MX8MM
#@DESCRIPTION: Machine configuration for IOTDIN-IMX8PLUS
#@MAINTAINER: compulab@compulab.co.il

require compulab-imx8mp.inc

KERNEL_DEVICETREE = " \
	compulab/iotdin-imx8p.dtb \
"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "iotdin-imx8p_defconfig,sdcard"
UBOOT_CONFIG[mfgtool] = "iotdin-imx8p_defconfig"
#
# Set u-boot DTB
UBOOT_DTB_NAME = "iotdin-imx8p.dtb"

KERNEL_CONFIG = "iotdin-imx8p_defconfig"

IMAGE_INSTALL:append = " iotd-imx8p-config nvme-cli fio smartmontools "

CORE_IMAGE_EXTRA_INSTALL += " gpsd gps-utils ppp modemmanager tree "

PREFERRED_VERSION_u-boot-compulab = "2023.04"
PREFERRED_VERSION_linux-compulab = "6.6.23"
PREFERRED_VERSION_libgpiod = "1.6.4"

CL_RELEASE = "2.0"
