#@TYPE: Machine
#@NAME: CompuLab ucm-imx8m-plus SBEV Evaluation Kit
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for CompuLab ucm-imx8m-plus EVK
#@MAINTAINER: compulab@compulab.co.il

require ucm-imx8m-plus.conf

KERNEL_DEVICETREE = " \
	compulab/ucm-imx8m-plus-sbev.dtb \ 
	compulab/ucm-imx8m-plus-som.dtb \ 
	compulab/sbev-ucmimx8plus.dtb \ 
	compulab/sbev-ucmimx8plus-dualhead.dtb \
	compulab/sbev-ucmimx8plus-hdmi.dtb \
	compulab/sbev-ucmimx8plus-headless.dtb \ 
	compulab/sbev-ucmimx8plus.dtbo \ 
	compulab/sbev-ucmimx8plus-cma.dtbo \
	compulab/sbev-ucmimx8plus-enet1.dtbo \
	compulab/sbev-ucmimx8plus-enet1-phy-id.dtbo \
	compulab/sbev-ucmimx8plus-leds.dtbo \ 
	compulab/sbev-ucmimx8plus-lvds.dtbo \ 
	compulab/sbev-ucmimx8plus-hdmi.dtbo \
	compulab/sbev-ucmimx8plus-mmc2.dtbo \ 
	compulab/sbev-ucmimx8plus-p15_spi.dtbo \ 
	compulab/sbev-ucmimx8plus-p16_i2c.dtbo \ 
	compulab/sbev-ucmimx8plus-p17_can.dtbo \ 
	compulab/sbev-ucmimx8plus-p18_gpio.dtbo \ 
	compulab/sbev-ucmimx8plus-p19_uart-b.dtbo \ 
	compulab/sbev-ucmimx8plus-p20_uart-a.dtbo \ 
	compulab/sbev-ucmimx8plus-wm8962.dtbo \ 
	compulab/sb-ucmimx8plus.dtbo \
	compulab/sbev-ucmimx8plus-csi1.dtbo \
	compulab/sbev-ucmimx8plus-csi2.dtbo \
"

UBOOT_CONFIG[sd] = "${MACHINE}_defconfig,sdcard"

CL_RELEASE = "compulab-1.0"
