SRC_URI_append = " \
	file://0000-compulab-imx8m-plus-Add-boards-support.patch \
	file://0001-compulab-imx8m-plus-Add-thermal-dtbs-files.patch \
	file://0002-imx8mp-compulab-Add-separate-device-tree-for-each-vi.patch \
	file://0003-imx8mp-compulab-Add-usbdev-device-tree.patch \
	file://0004-imx8mp-compulab-Add-rpmsg-device-tree.patch \
	file://0005-imx8mp-compulab-Enable-RAMDISK-support.patch \
	file://0006-compulab-dts-Refactoring-of-the-thermal-dtbs.patch \
	file://0007-compulab-dts-Refactoring-of-the-csi1-2.patch \
	file://0008-compulab-dts-Refactoring-of-the-csi1-2-1.patch \
	file://0009-ucm-imx219-Fix-reset-gpio.patch \
	file://0010-imx477-Add-driver-for-Sony-IMX477-sensor.patch \
	file://0011-compulab-ucm-dts-Add-IMX477-sample-device-tree.patch \
	file://defconfig \
"
