SRC_URI_append = " \
	file://0000-ucm-imx8m-plus-Add-board-support.patch \
	file://0001-ucm-imx8m-plus-Enable-LVDS-touch-screen.patch \
	file://0002-som-imx8m-plus-Add-board-support.patch \
	file://0003-som-imx8m-plus-dts-Change-i2c3-clock-frequency.patch \
	file://0004-som-imx8m-plus-dts-Enable-pm-support-on-usdhc1.patch \
	file://0005-spi-nor-winbond-Add-w25128dw-configuration-string.patch \
	file://0006-som-imx8m-plus-dts-Fix-the-flexspi-flash0-name.patch \
	file://defconfig \
"
