SRC_URI_append = " \
	file://0000-compulab-Add-ucm-imx8m-plus-support.patch \
	file://0001-compulab-ucm-imx8m-plus-dts-0-Update-device-tree.patch \
	file://0002-compulab-ucm-imx8m-plus-dts-1-Update-device-tree.patch \
	file://0003-compulab-ucm-imx8m-plus-dts-2-Update-device-tree.patch \
	file://0004-compulab-ucm-imx8m-plus-dts-3-Update-device-tree.patch \
	file://0005-compulab-ucm-imx8m-plus-dts-Move-wm8731-pca9555-to-i.patch \
	file://0006-compulab-ucm-imx8m-plus-dts-Fix-the-dsi-panel-reset.patch \
	file://0007-compulab-ucm-imx8m-plus-dts-pcie-Make-use-of-the-PLL.patch \
	file://0008-ucm-imx8m-plus-dts-Refactoring-with-respect-to-the-l.patch \
	file://0009-dts-Fix-lvds-compatibility-string.patch \
	file://0010-dts-typec-prepare-to.patch \
	file://0011-drivers-staging-Add-em9190-modem-driver.patch \
	file://0012-ucm-imx8m-plus-defconfig-Enable-em9190-module.patch \
	file://0013-ucm-imx8m-plus-dts-Enable-base-board-eeprom.patch \
	file://defconfig \
"
