SRC_URI:append = " \
	file://0000-compulab-Merge-5.15.32.patch \
	file://0001-compulab-Merge-5.15.32-add-files.patch \
	file://0002-net-phy-realtek-RTL8211E-make-use-of-realtek-clkout-.patch \
	file://0003-ucm-imx8m-plus-Update-defconfig.patch \
	file://0004-compulab-Add-common-compulab-config.patch \
	file://0005-som-imx8m-plus-dts-Update-device-tree.patch \
	file://0006-som-imx8m-plus-dts-Fix-usdhc2-performance-issue.patch \
	file://0007-ucm-imx8m-plus-dts-Update-device-tree.patch \
	file://0008-arm64-config-Add-compulab.config.patch \
	file://defconfig \
"
