#!/bin/bash -e

unset MACHINE DRAM COMPULAB_MACHINE

declare supported_machines=( ucm-imx8m-plus ucm-imx8m-plus-sbev mcm-imx8m-plus som-imx8m-plus iot-gate-imx8plus iotdin-imx8p )
_get_machine() {
    local select_string=${supported_machines[@]}" <<"
    PS3="MACHINE ? # > "
    select j in ${select_string}; do
        case ${j} in
            "<<")
            break
            ;;
            *)
            echo ${j}
            break
            ;;
            esac
    done
}

declare dram_configs=( D1 D2 D4 D8 )
_get_dram() {
    local select_string=${dram_configs[@]}" <<"
    PS3="DRAM Options ? # > "
    select j in ${select_string}; do
        case ${j} in
            "<<")
            break
            ;;
            *)
            echo ${j}
            break
            ;;
            esac
    done
}

MACHINE=${MACHINE:-$(_get_machine)}
if [[ -n ${MACHINE:-""} ]];then
DRAM=${DRAM:-$(_get_dram)}
if [[ -n ${DRAM:-""} ]];then
COMPULAB_MACHINE=${MACHINE}
DISTRO=${DISTRO:-fsl-imx-xwayland}
EULA=1
T="../sources/meta-bsp-imx8mp/templates"
M="../sources/meta-bsp-imx8mp/tools/${MACHINE}"

BD=$(cat <<< $@ | awk '$0=$NF')

function fix_fsl_imx_base() {
    F=${BUILDDIR}/../sources/meta-imx/meta-imx-sdk/conf/distro/include/fsl-imx-base.inc
    sed -i 's/\(^DISTRO_FEATURES:remove = ".*\)\(pulseaudio\)\(.*"\)/\1\3/g' ${F}
}

function mach_function() {
    [[ -d ${M} ]] || return 0
    for _file in ${M}/*;do
        source ${_file}
    done
}

function temp_function() {
    for _d in ${T}/*;do
        _file=$(basename ${_d})
        for _f in ${_d}/*;do
        file ${_f} | grep -iq "shell" && source ${_f} >> conf/${_file} || {
cat << eof >> conf/${_file}

# Included from ${_f}
$(cat ${_f})

eof
    }
        done;
    done
}

if [[ -d ${BD} ]];then

echo "Back to the build environment ${BD}"
. setup-environment ${BD}

else

. imx-setup-release.sh -b $@

    temp_function
    mach_function
    fix_fsl_imx_base
    MACHINE=${COMPULAB_MACHINE}
    unset COMPULAB_MACHINE
fi
else
cat << eof
DRAM: Declined setup ...
eof
fi
else
cat << eof
MACHINE: Declined setup ...
eof
fi
